Repository AuroraLegacy/elements, pull requests merged in 2020-12, with the labels that each got.

#16 Bug Fixes
  core/players-handbook/spells.xml
  supplements/tashas-cauldron-of-everything/spells.xml
Labels: bug

#18 Changes to UA files
  unearthed-arcana/2017/20170320.xml
  unearthed-arcana/2020/20200713.xml
Labels: Improvements

#22 [VGtM] monstrous-adventurers.xml file split and fix spacing
  supplements/volos-guide-to-monsters.index
  supplements/volos-guide-to-monsters/monstrous-adventurers.xml
  supplements/volos-guide-to-monsters/race-aasimar.xml
  supplements/volos-guide-to-monsters/race-bugbear.xml
  supplements/volos-guide-to-monsters/race-firbolg.xml
  supplements/volos-guide-to-monsters/race-goblin.xml
  supplements/volos-guide-to-monsters/race-hobgoblin.xml
  supplements/volos-guide-to-monsters/race-kenku.xml
  supplements/volos-guide-to-monsters/race-kobold.xml
  supplements/volos-guide-to-monsters/race-orc.xml
  supplements/volos-guide-to-monsters/race-yuantipureblood.xml
Labels: Improvements

#21 [TCOE] pre-Part 2
  core.index
  core/internal.xml
  core/sources.xml
  supplements/tashas-cauldron-of-everything.index
  supplements/tashas-cauldron-of-everything/options.xml
Labels: Improvements

#25 [TCOE] Update for the index to include Wild Magic Barbarian Subclass
  supplements/tashas-cauldron-of-everything.index
Labels: bug

#28 [MISC] Fix race-halforc.xml
  core/players-handbook/races/race-halforc.xml
Labels: bug

#29 [TCoE] Custom Lineage Fix
  supplements/tashas-cauldron-of-everything.index
Labels: Missing Content, bug
