Repository AuroraLegacy/elements, pull requests merged in 2021-01, with the labels that each got.

#37 [PHB] Tough Feat Fix
  core/players-handbook/feats.xml
Labels: bug

#36 [WDMM] Shield of the Uven Rune attunement fix
  supplements/waterdeep-dungeon-of-the-mad-mage/items.xml
Labels: bug

#34 [TCOE] Eldritch Adept fix
  supplements/tashas-cauldron-of-everything/feats.xml
Labels: bug

#26 [MISC] Artificer Infusion Update + Small Fixes
  core/dungeon-masters-guide.index
  core/dungeon-masters-guide/items/replicate-infusions.xml
  core/players-handbook/races/race-tiefling.xml
  supplements/eberron-rising-from-the-last-war/replicate-infusions.xml
  supplements/explorers-guide-to-wildemount.index
  supplements/explorers-guide-to-wildemount/replicate-infusions.xml
  supplements/ghosts-of-saltmarsh.index
  supplements/ghosts-of-saltmarsh/replicate-infusions.xml
  supplements/guildmasters-guide-to-ravnica.index
  supplements/guildmasters-guide-to-ravnica/replicate-infusions.xml
  supplements/rime-of-the-frostmaiden.index
  supplements/rime-of-the-frostmaiden/replicate-infusions.xml
  supplements/tashas-cauldron-of-everything.index
  supplements/tashas-cauldron-of-everything/archetypes/artificer-armorer.xml
  supplements/tashas-cauldron-of-everything/artificer-infusions.xml
  supplements/tashas-cauldron-of-everything/feats.xml
  supplements/tashas-cauldron-of-everything/items.xml
  supplements/tashas-cauldron-of-everything/spells.xml
  supplements/waterdeep-dungeon-of-the-mad-mage.index
  supplements/waterdeep-dungeon-of-the-mad-mage/replicate-infusions.xml
  supplements/xanathars-guide-to-everything.index
  supplements/xanathars-guide-to-everything/items/replicate-infusions.xml
Labels: Improvements, Missing Content

#39 [ERLW] Fixed typos in ERLW orc.xml
  supplements/eberron-rising-from-the-last-war/races/orc.xml
Labels: Community Submitted, Improvements, bug

#40 [UA] Corrected Combat Superiority Formatting
  unearthed-arcana/2016/20160404.xml
Labels: Community Submitted, Improvements

#44 [VGTM] Add level restriction to Aasimar Transformations
  supplements/volos-guide-to-monsters/race-aasimar.xml
Labels: bug

#45 [MISC] Fixed issue with Artificer Multiclass Slots not rounding up
  core/internal.xml
  supplements/eberron-rising-from-the-last-war/class-artificer.xml
Labels: bug
